name: Build and publish container

on:
  push:
    branches: [master, main]
  workflow_dispatch:
    inputs:
      reason:
        description: "Why ?"
        required: false
        default: ""

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: [aarch64, amd64, armv7hf]

    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: arribada/hostsetter-${{ matrix.arch }}
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
